version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/etc:/etc/rabbitmq/
      - ./rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: QueueUser
      RABBITMQ_DEFAULT_PASS: QueueUser00
      #RABBITMQ_DEFAULT_VHOST: dev
      RABBITMQ_LOG_BASE: "/var/log/rabbitmq"
      #RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.config
